#!/bin/bash
echo "Compiling the EBB-ADC overlay from .dts to .dtbo"
dtc -O dtb -o PRU-ADC-ADS8688-00A0.dtbo -b 0 -@ PRU-ADC-ADS8688.dts

echo "Building the PRU Clock code"
pasm -b PRUClock-ADS8688.p

echo "Building the PRU ADC code"
pasm -b PRUADC-ADS8688.p

echo "Building the PRU ADC binary application"
gcc PRUADC-ADS8688.c -o pruadc-ADS8688 -lpthread -lprussdrv

echo "Building the memory to file utility"
gcc mem2file-ADS8688.c -o mem2file-ADS8688
